title: Alfred Jijo
description: Software Engineering Student & Developer
# theme: jekyll-theme-minimal  
markdown: kramdown
permalink: /:title/
baseurl: "" 

# This allows a specific folder for projects
collections:
  projects:
    output: true

# Default definitions
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
