title: Alfred Jijo
description: Software Engineering Student & Developer
# theme: jekyll-theme-minimal
markdown: kramdown
permalink: /:title/
baseurl: ""

collections:
  projects:
    output: true

# Default definitions
defaults:
  - scope:
      path: ""
    values:
      layout: "default"